name: rspec

on: [pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: |
          # Install the appropriate version of Bundler based on Ruby version
          if [[ "${{ matrix.ruby-version }}" == "2.7" ]]; then
            gem install bundler -v 2.4.22
          else
            gem install bundler
          fi
          bundle install

      - name: Run RSpec
        run: |
          bundle exec rspec
